### ISSUE TITLE
Adicionar licença livre

### ISSUE THREAD

**Issue by pizzamaker** [cezarant/androidNetFlixSwitch#1]
Faltou especificar no projeto uma licença. Minha sugestão: criar um arquivo de texto tipo COPYING.md ou LICENSE.md com o texto da licença AGPLv3: https://www.gnu.org/licenses/agpl.html

**Comment by cezarant** [comment]
Olá amigo, obrigado pela sugestão. Infelizmente o meu conhecimento em
licenças e bem raso.
Me acostumei com o sourceforge q fazia este trabalho automático... rs

Vou acessar o link q você me forneceu e procurar um meio de adequar o
projeto. A ideia é q o mesmo seja livre, aberto pra qualquer pessoa
modificar, alterar e até expandir se for o caso. Acredito q a MIT ou Apache
Licence devem resolver.

De toda forma eu agradeço pela observação. Você participa do nosso grupo de
Facebook?
Em 26 de abr de 2016 11:19 AM, "pizzaiolo" <notifications@github.com>
escreveu:

**Comment by pizzamaker** [comment]
@cezarant Valeu pela rápida resposta! :) Qualquer licença livre já tá ótimo.

Não participo, encontrei o app de vcs pela busca do GitHub e queria pedir pra vcs adicionarem o app no F-Droid, que é um catálogo de apps livres: https://f-droid.org/

**Comment by cezarant** [comment]
Eu agradeço o contato. E inclusive agradeço bastante a oportunidade de
integrar o seu catálogo.
Porém, não acredito que seja benéfico integrá-lo pelo seguinte motivo:

Este aplicativo em si é apenas uma parte de um projeto de hardware livre.
Sem as outras peças, desenvolvidas em Arduíno e sem os bases para serem
desenhadas na impressora 3d, não acredito que ele vá ter muito benefício ao
usuário.

Se quiser mais detalhes a respeito do projeto completo, há este link
<https://cezarantsouza.wordpress.com/2016/03/15/minha-experiencia-com-a-implementacao-do-netflix-switch/>
e
este <https://www.youtube.com/watch?v=TTlIGdlbTy4>, que foi onde nós nos
inspiramos para fazer a ideia.

Possuo um outro aplicativo livre
<https://play.google.com/store/apps/details?id=com.deezer.sdk.sample&hl=pt-BR>,
(porém para ensinar música).
Assim que tiver uma folguinha aqui vou dar uma olhada lá, para ver como
posso fazer para integrá-lo ao seu catálogo.

Agradeço desde já pelo contato , um abraço e parabéns pelo trabalho.
Cézar


2016-04-26 11:36 GMT-03:00 pizzaiolo <notifications@github.com>:

> @cezarant <https://github.com/cezarant> Valeu pela rápida resposta! :)
> Qualquer licença livre já tá ótimo.
>
> Não participo, encontrei o app de vcs pela busca do GitHub e queria pedir
> pra vcs adicionarem o app no F-Droid, que é um catálogo de apps livres:
> https://f-droid.org/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cezarant/androidNetFlixSwitch/issues/1#issuecomment-214765972>
>



-- 
Como estou programando? Visite http://ouvidoperfeito.besaba.com/new/ e dê
um feedback!
"Complexidade sufoca, simplicidade liberta!".
Telefone: 9938-6618

**Comment by pizzamaker** [comment]
Ahh legal, valeu por avisar :)
Na verdade o catálogo nem é meu, eu só sou um voluntário no projeto. Vou te dar um toque lá no seu outro repo então.

Abraço!

**Comment by cezarant** [comment]
<a href="https://github.com/cezarant/androidNetFlixSwitch/blob/master/LICENSE.md ">Licença</a> criada  :) ``
